# Generated by Django 3.1.2 on 2020-10-08 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20201008_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Profile',
        ),
    ]
