# Generated by Django 3.1.2 on 2020-10-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201008_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
