# Generated by Django 3.1.2 on 2020-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201009_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='', max_length=15),
        ),
    ]
