# Generated by Django 3.1.2 on 2020-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='', max_length=15),
        ),
    ]
