# Generated by Django 3.1.2 on 2020-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_auto_20201009_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('paid', 'paid'), ('not-paid', 'not-paid')], default='', max_length=15),
        ),
    ]
