# Generated by Django 3.1.2 on 2020-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_auto_20201009_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domain',
            field=models.CharField(choices=[('software', 'software'), ('hardware', 'hardware')], default='', max_length=15),
        ),
    ]
