# Generated by Django 3.1.2 on 2020-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_auto_20201011_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='domain',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], default='', max_length=15),
        ),
    ]
