# Generated by Django 3.1.2 on 2020-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_auto_20201015_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='domain',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
